fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  view:
    serialize_null: true
    view_response_listener:  true
  exception:
    exception_controller: 'fos_rest.exception.controller::showAction'
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: "^/api", prefer_extension: true, fallback_format: json, priorities: [ json ] }
  versioning: true