security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
    providers:
        api_login_provider:
            id: login_provider_api_service

    firewalls:

        api_doc:
            pattern: /api/doc
            security: false
        api_account_creation:
            pattern: ^/api/user/account
            security: false
        api_login:
            pattern: ^/api/user/login
            stateless: true
            provider: api_login_provider
            guard:
                authenticators:
                    - username_password_authenticator
        api:
            pattern: ^/api
            security: false
#            stateless: true
#            provider: api_login_provider
#            guard:
#                authenticators:
#                    - jwt.authenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/api, roles: ROLE_USER }
